Repository RehanSaeed/EditorConfig, pull requests merged in 2020-11, with the labels that each got.

#39 Add severity to modifier order
  .editorconfig
Labels: bug, patch

#41 Rename master branch to main
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release-drafter.yml
  README.md
Labels: maintenance, patch

#42 Add Support for VS 16.8 Which Introduced Breaking Changes
  .editorconfig
Labels: enhancement, major
