Repository RehanSaeed/EditorConfig, pull requests merged in 2020-07, with the labels that each got.

#32 Add Automatic Drafting of Releases
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: maintenance, patch

#29 Add samples to verify intended behaviors
  Samples/CSharp/CSharpSamples.csproj
  Samples/CSharp/CSharpSamples.ruleset
  Samples/CSharp/CSharpSamples.sln
  Samples/CSharp/FieldsExamples.cs
  Samples/CSharp/packages.config
  Samples/CSharp/stylecop.json
Labels: enhancement, patch

#33 Add File Headers Configuration
  .editorconfig
  Samples/CSharp/CSharpSamples.csproj
  Samples/CSharp/CSharpSamples.ruleset
  Samples/CSharp/CSharpSamples.sln
  Samples/CSharp/FieldsExamples.cs
  Samples/CSharp/packages.config
  Samples/CSharp/stylecop.json
Labels: enhancement, minor
